#!/bin/sh
#
# Hook script to link code and prevent commit if linting failed.
# Called by "git commit" with no arguments. The hook should
# exit with non-zero status after issuing an appropriate message if
# linting is failed and it wants to stop the commit.

if !(npm run lint --silent) then
	exit 1	
fi

exit 0
